
server:
  port: 8080


spring:
  application:
    name: TaskManagerAPIThymeleaf
  datasource:
    url: jdbc:mysql://mysql:3306/task-manager-database?createDatabaseIfNotExist=true
    username: root
    password: five2one
  jpa:
    hibernate:
      ddl-auto: update

